// apps/solid/src/routes/qui-suis-je.tsx
import { readAboutPage } from "@ec/domain/pages";
import { Section, SectionContent, SectionImage, SectionMain, SectionTitle } from "@ec/ui/section";
import { createFileRoute } from "@tanstack/solid-router";
import { For } from "solid-js";

// ROUTE -----------------------------------------------------------------------------------------------------------------------------------
export const Route = createFileRoute("/qui-suis-je")({
  component: RouteComponent,
  loader: () => readAboutPage(),
});

// PAGE ------------------------------------------------------------------------------------------------------------------------------------
function RouteComponent() {
  const data = Route.useLoaderData();
  const intents = ["default", "secondary", "primary"] as const;

  return (
    <For each={data()}>
      {({ content, img, title }, i) => (
        <Section
          class={{ container: `lg:items-center ${i() % 2 === 0 ? "" : "lg:flex-row-reverse"}` }}
          intent={intents[i()]}
          reverse={i() % 2 !== 0}
        >
          <SectionMain class="basis-1/2">
            <SectionTitle title={title} />
            <SectionContent>{content}</SectionContent>
          </SectionMain>
          <SectionImage class={{ figure: "flex basis-1/2" }} image={img} />
        </Section>
      )}
    </For>
  );
}

// apps/web/src/routes/qui-suis-je/index.tsx
import { readAboutPage } from "@ec/domain/helpers/pages";
import { Hero, HeroContent } from "@ec/ui/components/hero";
import {
  Section,
  SectionContent,
  SectionImage,
  SectionMain,
  SectionTitle,
  type SectionProps,
  type SectionTitleProps,
} from "@ec/ui/components/section";
import { createFileRoute } from "@tanstack/react-router";
import { cva } from "class-variance-authority";

import { seoHead } from "@/seo/head";

// ROUTE -----------------------------------------------------------------------------------------------------------------------------------
export const Route = createFileRoute("/qui-suis-je/")({
  component: RouteComponent,
  head: () =>
    seoHead({
      description: "Découvre le parcours, les inspirations et la démarche artistique d’Eliana Corré, artiste peintre réunionnaise.",
      image: "https://ik.imagekit.io/elianacorre/decouvrez-mon-parcours.jpg",
      path: "/qui-suis-je",
      title: "À propos d’Eliana Corré — Parcours et inspirations",
    }),
  loader: () => readAboutPage(),
});

// STYLES ----------------------------------------------------------------------------------------------------------------------------------
const PAGE = {
  aside: cva("flex basis-1/2 lg:translate-x-8"),
  heroContent: cva("text-base text-justify text-pretty sm:text-lg lg:text-justify"),
  main: cva("basis-1/2"),
};

// PAGE ------------------------------------------------------------------------------------------------------------------------------------
function RouteComponent() {
  const { hero, items } = Route.useLoaderData();
  const sections: SectionProps[] = [{ intent: "secondary" }, { intent: "primary" }];
  const titles: Pick<SectionTitleProps, "intent">[] = [{ intent: "secondary" }, {}];

  return (
    <>
      <Hero image={hero?.img} title={hero?.title ?? []} className={{ aside: PAGE.aside(), main: PAGE.main() }}>
        <HeroContent className={PAGE.heroContent()}>
          {hero?.content.map((paragraph, i) => (
            <p key={i}>{paragraph}</p>
          ))}
        </HeroContent>
      </Hero>
      {items.map(({ content, img, slug, title }, i) => (
        <Section
          key={slug}
          className={{ container: `lg:items-center ${i % 2 === 0 ? "lg:flex-row-reverse" : ""}` }}
          reverse={i % 2 === 0}
          {...sections[i]}
        >
          <SectionMain className={PAGE.main()}>
            <SectionTitle title={title} {...titles[i]} />
            <SectionContent>
              {content.map((paragraph, j) => (
                <p key={j}>{paragraph}</p>
              ))}
            </SectionContent>
          </SectionMain>
          <SectionImage className={{ figure: "flex basis-1/2" }} image={img} />
        </Section>
      ))}
    </>
  );
}
